version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - SOLR_URL=http://solr:8983
    depends_on:
      - solr

  solr:
    image: solr:9.7.0-slim
    ports:
      - "8983:8983"
    volumes:
      - ./solr/schema.xml:/opt/solr/server/solr/briw/conf/schema.xml
      - ./solr/solrconfig.xml:/opt/solr/server/solr/briw/conf/solrconfig.xml
    command:
      - solr-precreate
      - briw

volumes:
  solr_data: