services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - SOLR_URL=http://host.docker.internal:8983/solr/briw
    volumes:
      - ./backend/uploads:/app/uploads
